name: Release
on: workflow_dispatch

permissions: write-all

jobs:
  build-android:
    uses: ./.github/workflows/android.yml
  build-ios:
    uses: ./.github/workflows/ios.yml

  Releaser:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
          name: Gorefield-V2 Android
          path: ${{ github.workspace }}

      - name: Move Android File
        run: mv "${{ github.workspace }}/Gorefield V2-release.apk" "${{ github.workspace }}/Gorefield V2-Android.apk"

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: Gorefield V2 iOS
          path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv "${{ github.workspace }}/Gorefield V2-release.ipa" "${{ github.workspace }}/Gorefield V2-release.ipa"

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "v2.1.1"
          tag_name: "v2.1.1"
          prerelease: false
          files: |
            ${{ github.workspace }}/*.apk
            ${{ github.workspace }}/*.ipa
