name: Release

on:
  workflow_dispatch:

permissions: write-all

jobs:
  build-android:
    uses: ./.github/workflows/android.yml

  build-ios:
    uses: ./.github/workflows/ios.yml

  release:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest

    steps:
      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: Gorefield-V2-Android
          path: artifacts

      - name: Download iOS artifact
        uses: actions/download-artifact@v4
        with:
          name: Gorefield-V2-iOS
          path: artifacts

      - name: List files (debug)
        run: ls -R artifacts

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.1.1
          name: v2.1.1
          prerelease: false
          files: |
            artifacts/**/*.apk
            artifacts/**/*.ipa
